### ISSUE TITLE
404 on phobos tag - Repository Signing and App Registry will be removed from quay.io.

### ISSUE THREAD

**Issue by ivanddiaz** [tcarland/spark-hs-chart#10]
Hi,

Thanks for sharing this, is the only no-brainer chart which works flawless :)

I want to ask about one problem I've found, and a petition. First:

quay.io/tcarland/spark:v3.2.1-phobos-2205.01 doesn't exists, and older releases pointed to docker hub which haven't any image.

What do you think about to move images to another public repo or maybe can you share the dockerfile?

Great chart. Thanks so much!

**Comment by tcarland** [comment]
My bad!  I use an alternate internal registry when testing and forgot to actually push the image to quay.io.  I just pushed it now to quay.io. There should also be other quay.io images and the tags mneme or thebe, both spark v3.2.1, should work fine as well. phobos should be available in about 10 minutes.

**Comment by tcarland** [comment]
I use the one from the spark distribution and have added some notes to the README on how to build using spark's image tool.

**Comment by ivanddiaz** [comment]
Thank you!
