### ISSUE TITLE
TLS/SSL - Issue

### ISSUE THREAD

**Issue by ananth-sabhapathi** [tcarland/spark-hs-chart#26]
Hello There

Could you please elaborate more about TLS and SSL part? I am still not understanding the DNS part here.

SAN name should be anyone of the below?

DNS:spark-hs.spark.svc.cluster.local
DNS:*.spark.svc.cluster.local
DNS:spark-hs.spark
DNS:spark-hs.spark.svc

**Comment by tcarland** [comment]
Sorry, I missed this post.

  This serves as a *list* of SubjectAlternateName values to be set in the Certificate.  The first listed there, `spark-hs.spark.svc.cluster.local` is the fqdn for the internal k8s service. For a given k8s cluster, the default internal domain is cluster.local, and services follow the pattern of _svcname.namespace_.svc.cluster.local.  If you intend to expose the service externally (by way of loadbalancer), then you would also want to add the fqdn of the IP assigned as the external address.

The additional SAN fields allow services to refer to themselves simply as <svcname> or by the dns shortname, not fully qualified, where the domain is assumed (within the cluster).
